### ISSUE TITLE
Animated connections

### ISSUE THREAD

**Issue by CRY-D** [chrisjpatty/flume#235]
If you want to add a simple animated connection similar to the one shown above, you can use the following CSS snippet

![Screenshot_20240102_145422](https://github.com/chrisjpatty/flume/assets/16564491/6e0c3669-33e1-409b-9530-3119c036849c)
```css
.Connection_svg__-fKLY {
      stroke-dasharray:5;
      animation: dashdraw .5s linear infinite;
}
@keyframes dashdraw {
    0% { stroke-dashoffset: 10   }
 }
```
